// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
)

type User struct {
	ID                            uuid.UUID
	Username                      string
	PasswordHash                  string
	Highscore                     int32
	FingerprintScannerHashCode    string
	FingerprintScannerAccessLevel string
}
