// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, password_hash, highscore, fingerprint_scanner_hash_code, fingerprint_scanner_access_level)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    0,
    $3,
    $4
)
RETURNING id, username, password_hash, highscore, fingerprint_scanner_hash_code, fingerprint_scanner_access_level
`

type CreateUserParams struct {
	Username                      string
	PasswordHash                  string
	FingerprintScannerHashCode    string
	FingerprintScannerAccessLevel string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.FingerprintScannerHashCode,
		arg.FingerprintScannerAccessLevel,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Highscore,
		&i.FingerprintScannerHashCode,
		&i.FingerprintScannerAccessLevel,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, highscore, fingerprint_scanner_hash_code, fingerprint_scanner_access_level FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Highscore,
		&i.FingerprintScannerHashCode,
		&i.FingerprintScannerAccessLevel,
	)
	return i, err
}

const getUserFromFingerHashCode = `-- name: GetUserFromFingerHashCode :one
SELECT id, username, password_hash, highscore, fingerprint_scanner_hash_code, fingerprint_scanner_access_level FROM users WHERE fingerprint_scanner_hash_code = $1
`

func (q *Queries) GetUserFromFingerHashCode(ctx context.Context, fingerprintScannerHashCode string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromFingerHashCode, fingerprintScannerHashCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Highscore,
		&i.FingerprintScannerHashCode,
		&i.FingerprintScannerAccessLevel,
	)
	return i, err
}

const getUserFromId = `-- name: GetUserFromId :one
SELECT id, username, password_hash, highscore, fingerprint_scanner_hash_code, fingerprint_scanner_access_level FROM users
WHERE id = $1
`

func (q *Queries) GetUserFromId(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromId, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Highscore,
		&i.FingerprintScannerHashCode,
		&i.FingerprintScannerAccessLevel,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, password_hash, highscore, fingerprint_scanner_hash_code, fingerprint_scanner_access_level FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Highscore,
			&i.FingerprintScannerHashCode,
			&i.FingerprintScannerAccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHighScoreFromFingerPrintHash = `-- name: UpdateHighScoreFromFingerPrintHash :exec
UPDATE users
SET highscore = GREATEST(highscore, $1)
WHERE fingerprint_scanner_hash_code = $2
`

type UpdateHighScoreFromFingerPrintHashParams struct {
	Highscore                  int32
	FingerprintScannerHashCode string
}

func (q *Queries) UpdateHighScoreFromFingerPrintHash(ctx context.Context, arg UpdateHighScoreFromFingerPrintHashParams) error {
	_, err := q.db.ExecContext(ctx, updateHighScoreFromFingerPrintHash, arg.Highscore, arg.FingerprintScannerHashCode)
	return err
}

const updateHighScoreFromId = `-- name: UpdateHighScoreFromId :exec
UPDATE users
SET highscore = GREATEST(highscore, $1)
WHERE id = $2
`

type UpdateHighScoreFromIdParams struct {
	Highscore int32
	ID        uuid.UUID
}

func (q *Queries) UpdateHighScoreFromId(ctx context.Context, arg UpdateHighScoreFromIdParams) error {
	_, err := q.db.ExecContext(ctx, updateHighScoreFromId, arg.Highscore, arg.ID)
	return err
}
